version: "3.8"

volumes:
  static_webviz:

services:
  app-scene-viewer:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    image: registry.gitlab.com/dataware-tools/app-scene-viewer:latest
    ports:
      - 8080:8080
    volumes:
      - .:/app
#      - static_webviz:/app/__static_webviz__
    entrypoint: "/app/docker-entrypoint.sh"
#    command: ["/app/node_modules/http-server/bin/http-server", "__static_webviz__"]
    command:
      - npm
      - run
      - serve-static-webviz
    tty: true