# Spin rate (refresh rate)
spin_rate: 2  # Hz

# File reader
file_reader:
  mapping:  # from: to
    start_timestamp: timestamp
  filtering:
    - timestamp
    - caption

# Topic aggregator
topic_aggregator:
  input:
    base_topic: "/scene_viewer/scene_captions"
    topics:
      /scene_viewer/scene_captions:
        dtype: dict
      /scene_viewer/vehicle_trajectory:
        dtype: list
        columns:
          - timestamp
          - latitude
          - longitude
          - altitude
  output:
    dtype: dict
    columns:
      - timestamp
      - caption
      - latitude
      - longitude
      - altitude