name: Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 300

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          token: ${{secrets.REPO_ACCESS_TOKEN}}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: bootstrap repository
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{secrets.REPO_ACCESS_TOKEN}}

      - name: Test app
        run: yarn run test
