name: Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 300

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          token: ${{secrets.REPO_ACCESS_TOKEN}}
          lfs: true

      - name: Set up node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: bootstrap repository
        run: yarn install --immutable
        env:
          NODE_AUTH_TOKEN: ${{secrets.REPO_ACCESS_TOKEN}}

      - name: Test app
        run: yarn run test
